name: Invitation to the DEVs Dungeon GitHub Community Organization
description: I would like to be part of the developers community
title: "Please invite me to the DEVs Dungeon GitHub Community Organization"
labels: [invite me to the organisation]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: input
    id: discordname
    attributes:
      label: Discord Username (if applicable)
      placeholder: Insert your Discord username here
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: What do you like about this community/Why do you want to join?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Join our Discord Community [here](https://discord.gg/ceMXzhfaka) to interact with 5k+ Developers from across the world!
        Follow our LinkedIn Page [here](https://www.linkedin.com/company/devs-dungeon) for Internships, Jobs, Workshops, Events updates! 
        Feel free to check out our Bio Link [here](https://devs-dungeon.github.io/bio/) 🔥
