name: Open Source Project Review
description: Please review my project on a livestream
title: "[REVIEW] <project name here>"
labels: [open source review, live stream review]
body:
  - type: markdown
    attributes:
      value: "Your project doesn't have to be hosted at GitHub, it can also be on GitLab or other VCS"
  - type: input
    id: link
    attributes:
      label: Project link
      placeholder: https://github.com/<your-username>/<project-name>
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Join our Discord Community [here](https://discord.gg/ceMXzhfaka)
        Follow us on LinkedIn [here](https://www.linkedin.com/company/devs-dungeon)
        Follow us on Twitter [here](https://twitter.com/devs_dungeon)
        Feel free to check out other cool repositories of the DEVs Dungeon Community [here](https://github.com/Devs-Dungeon)
