name: Resume Review
description: Please review my resume on a live stream
title: "[REVIEW]"
labels: [resume review, live stream review]
body:
  - type: markdown
    attributes:
      value: "**Remove all personal data, otherwise, the resume will be deleted**"
  - type: input
    id: link
    attributes:
      label: Resume link
      placeholder: "e.g.: https://drive.google.com/file/d/<file-id>/view"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Join our Discord Community [here](https://discord.gg/ceMXzhfaka)
        Follow us on LinkedIn [here](https://www.linkedin.com/company/devs-dungeon)
        Follow us on Twitter [here](https://twitter.com/devs_dungeon)
        Feel free to check out other cool repositories of the DEVs Dungeon Community [here](https://github.com/Devs-Dungeon)
